### ISSUE TITLE
Did you ever manage to properly fix the EOF problem?

### ISSUE THREAD

**Issue by LucasVanDongen** [chadacious/exoplayernetflix#1]
Hi I found your profile and this repo through the following issue: https://github.com/google/ExoPlayer/issues/7630

It helped me a lot to get Netflix content playing. But did you ever get around fixing stuff like seeking?

**Comment by chadacious** [comment]
At this time, I am still just swallowing the EOF exception in the IntitializationChunk.java of the exoplayer, which is working for my purposes. I have not "properly" resolved the issue, which I think is to determe the correct Segment indexRanges, but by using a custom exoplayer with the error handling mod and specifying a wide enough indexRange to ensure I get the sidx box, netflix seems to be streaming perfectly fine.
I have amazon, youtube, disney+ and hulu all streaming correctly with the stock exoplayer (without any exoplayer modifications). Exo player handles all of them quite well. Its just netflix that has this odd problem.

**Comment by LucasVanDongen** [comment]
I have to see what will come up next, probably I need to be able to start at any place in the video. But for now I got it working so thank!

**Comment by chadacious** [comment]
Seek is working fine on my side. I think the only things necessary is specify a wide enough indexRange and to swallow the error in exoplayer as I described.
